package com.fruit.app.model;

import java.util.Date;

public class TGoodsScore {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_score.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_score.goods_id
     *
     * @mbg.generated
     */
    private String goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_score.goods_name
     *
     * @mbg.generated
     */
    private String goodsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_score.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_score.nick_name
     *
     * @mbg.generated
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_score.score_type
     *
     * @mbg.generated
     */
    private Boolean scoreType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_score.score
     *
     * @mbg.generated
     */
    private Byte score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_score.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_score.update_date
     *
     * @mbg.generated
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_score.is_delete
     *
     * @mbg.generated
     */
    private Boolean isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_score.data_from
     *
     * @mbg.generated
     */
    private Byte dataFrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_score.comment
     *
     * @mbg.generated
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_score.id
     *
     * @return the value of t_goods_score.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_score.id
     *
     * @param id the value for t_goods_score.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_score.goods_id
     *
     * @return the value of t_goods_score.goods_id
     *
     * @mbg.generated
     */
    public String getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_score.goods_id
     *
     * @param goodsId the value for t_goods_score.goods_id
     *
     * @mbg.generated
     */
    public void setGoodsId(String goodsId) {
        this.goodsId = goodsId == null ? null : goodsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_score.goods_name
     *
     * @return the value of t_goods_score.goods_name
     *
     * @mbg.generated
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_score.goods_name
     *
     * @param goodsName the value for t_goods_score.goods_name
     *
     * @mbg.generated
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_score.user_id
     *
     * @return the value of t_goods_score.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_score.user_id
     *
     * @param userId the value for t_goods_score.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_score.nick_name
     *
     * @return the value of t_goods_score.nick_name
     *
     * @mbg.generated
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_score.nick_name
     *
     * @param nickName the value for t_goods_score.nick_name
     *
     * @mbg.generated
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_score.score_type
     *
     * @return the value of t_goods_score.score_type
     *
     * @mbg.generated
     */
    public Boolean getScoreType() {
        return scoreType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_score.score_type
     *
     * @param scoreType the value for t_goods_score.score_type
     *
     * @mbg.generated
     */
    public void setScoreType(Boolean scoreType) {
        this.scoreType = scoreType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_score.score
     *
     * @return the value of t_goods_score.score
     *
     * @mbg.generated
     */
    public Byte getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_score.score
     *
     * @param score the value for t_goods_score.score
     *
     * @mbg.generated
     */
    public void setScore(Byte score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_score.create_date
     *
     * @return the value of t_goods_score.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_score.create_date
     *
     * @param createDate the value for t_goods_score.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_score.update_date
     *
     * @return the value of t_goods_score.update_date
     *
     * @mbg.generated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_score.update_date
     *
     * @param updateDate the value for t_goods_score.update_date
     *
     * @mbg.generated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_score.is_delete
     *
     * @return the value of t_goods_score.is_delete
     *
     * @mbg.generated
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_score.is_delete
     *
     * @param isDelete the value for t_goods_score.is_delete
     *
     * @mbg.generated
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_score.data_from
     *
     * @return the value of t_goods_score.data_from
     *
     * @mbg.generated
     */
    public Byte getDataFrom() {
        return dataFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_score.data_from
     *
     * @param dataFrom the value for t_goods_score.data_from
     *
     * @mbg.generated
     */
    public void setDataFrom(Byte dataFrom) {
        this.dataFrom = dataFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_score.comment
     *
     * @return the value of t_goods_score.comment
     *
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_score.comment
     *
     * @param comment the value for t_goods_score.comment
     *
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}