package com.fruit.app.model;

import java.math.BigDecimal;
import java.util.Date;

public class TGoods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.goods_name
     *
     * @mbg.generated
     */
    private String goodsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.goods_type
     *
     * @mbg.generated
     */
    private Byte goodsType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.price
     *
     * @mbg.generated
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.unit
     *
     * @mbg.generated
     */
    private String unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.goods_status
     *
     * @mbg.generated
     */
    private Byte goodsStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.googs_desc
     *
     * @mbg.generated
     */
    private String googsDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.default_pic_url
     *
     * @mbg.generated
     */
    private String defaultPicUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.position_name
     *
     * @mbg.generated
     */
    private String positionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.position
     *
     * @mbg.generated
     */
    private String position;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.open_date
     *
     * @mbg.generated
     */
    private Date openDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.close_date
     *
     * @mbg.generated
     */
    private Date closeDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.close_reason
     *
     * @mbg.generated
     */
    private String closeReason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.update_date
     *
     * @mbg.generated
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.is_delete
     *
     * @mbg.generated
     */
    private Boolean isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.data_from
     *
     * @mbg.generated
     */
    private Byte dataFrom;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.id
     *
     * @return the value of t_goods.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.id
     *
     * @param id the value for t_goods.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.user_id
     *
     * @return the value of t_goods.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.user_id
     *
     * @param userId the value for t_goods.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.goods_name
     *
     * @return the value of t_goods.goods_name
     *
     * @mbg.generated
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.goods_name
     *
     * @param goodsName the value for t_goods.goods_name
     *
     * @mbg.generated
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.goods_type
     *
     * @return the value of t_goods.goods_type
     *
     * @mbg.generated
     */
    public Byte getGoodsType() {
        return goodsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.goods_type
     *
     * @param goodsType the value for t_goods.goods_type
     *
     * @mbg.generated
     */
    public void setGoodsType(Byte goodsType) {
        this.goodsType = goodsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.price
     *
     * @return the value of t_goods.price
     *
     * @mbg.generated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.price
     *
     * @param price the value for t_goods.price
     *
     * @mbg.generated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.unit
     *
     * @return the value of t_goods.unit
     *
     * @mbg.generated
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.unit
     *
     * @param unit the value for t_goods.unit
     *
     * @mbg.generated
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.goods_status
     *
     * @return the value of t_goods.goods_status
     *
     * @mbg.generated
     */
    public Byte getGoodsStatus() {
        return goodsStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.goods_status
     *
     * @param goodsStatus the value for t_goods.goods_status
     *
     * @mbg.generated
     */
    public void setGoodsStatus(Byte goodsStatus) {
        this.goodsStatus = goodsStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.googs_desc
     *
     * @return the value of t_goods.googs_desc
     *
     * @mbg.generated
     */
    public String getGoogsDesc() {
        return googsDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.googs_desc
     *
     * @param googsDesc the value for t_goods.googs_desc
     *
     * @mbg.generated
     */
    public void setGoogsDesc(String googsDesc) {
        this.googsDesc = googsDesc == null ? null : googsDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.default_pic_url
     *
     * @return the value of t_goods.default_pic_url
     *
     * @mbg.generated
     */
    public String getDefaultPicUrl() {
        return defaultPicUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.default_pic_url
     *
     * @param defaultPicUrl the value for t_goods.default_pic_url
     *
     * @mbg.generated
     */
    public void setDefaultPicUrl(String defaultPicUrl) {
        this.defaultPicUrl = defaultPicUrl == null ? null : defaultPicUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.position_name
     *
     * @return the value of t_goods.position_name
     *
     * @mbg.generated
     */
    public String getPositionName() {
        return positionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.position_name
     *
     * @param positionName the value for t_goods.position_name
     *
     * @mbg.generated
     */
    public void setPositionName(String positionName) {
        this.positionName = positionName == null ? null : positionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.position
     *
     * @return the value of t_goods.position
     *
     * @mbg.generated
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.position
     *
     * @param position the value for t_goods.position
     *
     * @mbg.generated
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.open_date
     *
     * @return the value of t_goods.open_date
     *
     * @mbg.generated
     */
    public Date getOpenDate() {
        return openDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.open_date
     *
     * @param openDate the value for t_goods.open_date
     *
     * @mbg.generated
     */
    public void setOpenDate(Date openDate) {
        this.openDate = openDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.close_date
     *
     * @return the value of t_goods.close_date
     *
     * @mbg.generated
     */
    public Date getCloseDate() {
        return closeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.close_date
     *
     * @param closeDate the value for t_goods.close_date
     *
     * @mbg.generated
     */
    public void setCloseDate(Date closeDate) {
        this.closeDate = closeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.close_reason
     *
     * @return the value of t_goods.close_reason
     *
     * @mbg.generated
     */
    public String getCloseReason() {
        return closeReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.close_reason
     *
     * @param closeReason the value for t_goods.close_reason
     *
     * @mbg.generated
     */
    public void setCloseReason(String closeReason) {
        this.closeReason = closeReason == null ? null : closeReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.create_date
     *
     * @return the value of t_goods.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.create_date
     *
     * @param createDate the value for t_goods.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.update_date
     *
     * @return the value of t_goods.update_date
     *
     * @mbg.generated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.update_date
     *
     * @param updateDate the value for t_goods.update_date
     *
     * @mbg.generated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.is_delete
     *
     * @return the value of t_goods.is_delete
     *
     * @mbg.generated
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.is_delete
     *
     * @param isDelete the value for t_goods.is_delete
     *
     * @mbg.generated
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.data_from
     *
     * @return the value of t_goods.data_from
     *
     * @mbg.generated
     */
    public Byte getDataFrom() {
        return dataFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.data_from
     *
     * @param dataFrom the value for t_goods.data_from
     *
     * @mbg.generated
     */
    public void setDataFrom(Byte dataFrom) {
        this.dataFrom = dataFrom;
    }
}