package com.fruit.app.model;

import java.math.BigDecimal;
import java.util.Date;

public class TSysLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_log.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_log.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_log.goods_id
     *
     * @mbg.generated
     */
    private String goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_log.goods_name
     *
     * @mbg.generated
     */
    private String goodsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_log.fun_name
     *
     * @mbg.generated
     */
    private String funName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_log.log_level
     *
     * @mbg.generated
     */
    private Byte logLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_log.log_type
     *
     * @mbg.generated
     */
    private Byte logType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_log.log_ip
     *
     * @mbg.generated
     */
    private String logIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_log.longitude
     *
     * @mbg.generated
     */
    private BigDecimal longitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_log.latitude
     *
     * @mbg.generated
     */
    private BigDecimal latitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_log.position_name
     *
     * @mbg.generated
     */
    private String positionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_log.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_log.update_date
     *
     * @mbg.generated
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_log.data_from
     *
     * @mbg.generated
     */
    private Byte dataFrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_log.logcontent
     *
     * @mbg.generated
     */
    private String logcontent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_log.id
     *
     * @return the value of t_sys_log.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_log.id
     *
     * @param id the value for t_sys_log.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_log.user_id
     *
     * @return the value of t_sys_log.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_log.user_id
     *
     * @param userId the value for t_sys_log.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_log.goods_id
     *
     * @return the value of t_sys_log.goods_id
     *
     * @mbg.generated
     */
    public String getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_log.goods_id
     *
     * @param goodsId the value for t_sys_log.goods_id
     *
     * @mbg.generated
     */
    public void setGoodsId(String goodsId) {
        this.goodsId = goodsId == null ? null : goodsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_log.goods_name
     *
     * @return the value of t_sys_log.goods_name
     *
     * @mbg.generated
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_log.goods_name
     *
     * @param goodsName the value for t_sys_log.goods_name
     *
     * @mbg.generated
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_log.fun_name
     *
     * @return the value of t_sys_log.fun_name
     *
     * @mbg.generated
     */
    public String getFunName() {
        return funName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_log.fun_name
     *
     * @param funName the value for t_sys_log.fun_name
     *
     * @mbg.generated
     */
    public void setFunName(String funName) {
        this.funName = funName == null ? null : funName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_log.log_level
     *
     * @return the value of t_sys_log.log_level
     *
     * @mbg.generated
     */
    public Byte getLogLevel() {
        return logLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_log.log_level
     *
     * @param logLevel the value for t_sys_log.log_level
     *
     * @mbg.generated
     */
    public void setLogLevel(Byte logLevel) {
        this.logLevel = logLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_log.log_type
     *
     * @return the value of t_sys_log.log_type
     *
     * @mbg.generated
     */
    public Byte getLogType() {
        return logType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_log.log_type
     *
     * @param logType the value for t_sys_log.log_type
     *
     * @mbg.generated
     */
    public void setLogType(Byte logType) {
        this.logType = logType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_log.log_ip
     *
     * @return the value of t_sys_log.log_ip
     *
     * @mbg.generated
     */
    public String getLogIp() {
        return logIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_log.log_ip
     *
     * @param logIp the value for t_sys_log.log_ip
     *
     * @mbg.generated
     */
    public void setLogIp(String logIp) {
        this.logIp = logIp == null ? null : logIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_log.longitude
     *
     * @return the value of t_sys_log.longitude
     *
     * @mbg.generated
     */
    public BigDecimal getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_log.longitude
     *
     * @param longitude the value for t_sys_log.longitude
     *
     * @mbg.generated
     */
    public void setLongitude(BigDecimal longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_log.latitude
     *
     * @return the value of t_sys_log.latitude
     *
     * @mbg.generated
     */
    public BigDecimal getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_log.latitude
     *
     * @param latitude the value for t_sys_log.latitude
     *
     * @mbg.generated
     */
    public void setLatitude(BigDecimal latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_log.position_name
     *
     * @return the value of t_sys_log.position_name
     *
     * @mbg.generated
     */
    public String getPositionName() {
        return positionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_log.position_name
     *
     * @param positionName the value for t_sys_log.position_name
     *
     * @mbg.generated
     */
    public void setPositionName(String positionName) {
        this.positionName = positionName == null ? null : positionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_log.create_date
     *
     * @return the value of t_sys_log.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_log.create_date
     *
     * @param createDate the value for t_sys_log.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_log.update_date
     *
     * @return the value of t_sys_log.update_date
     *
     * @mbg.generated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_log.update_date
     *
     * @param updateDate the value for t_sys_log.update_date
     *
     * @mbg.generated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_log.data_from
     *
     * @return the value of t_sys_log.data_from
     *
     * @mbg.generated
     */
    public Byte getDataFrom() {
        return dataFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_log.data_from
     *
     * @param dataFrom the value for t_sys_log.data_from
     *
     * @mbg.generated
     */
    public void setDataFrom(Byte dataFrom) {
        this.dataFrom = dataFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_log.logcontent
     *
     * @return the value of t_sys_log.logcontent
     *
     * @mbg.generated
     */
    public String getLogcontent() {
        return logcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_log.logcontent
     *
     * @param logcontent the value for t_sys_log.logcontent
     *
     * @mbg.generated
     */
    public void setLogcontent(String logcontent) {
        this.logcontent = logcontent == null ? null : logcontent.trim();
    }
}