package com.fruit.app.model;

import java.util.Date;

public class TUserViainfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_viainfo.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_viainfo.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_viainfo.receiver
     *
     * @mbg.generated
     */
    private String receiver;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_viainfo.via_type
     *
     * @mbg.generated
     */
    private Byte viaType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_viainfo.via_text
     *
     * @mbg.generated
     */
    private String viaText;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_viainfo.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_viainfo.expire_date
     *
     * @mbg.generated
     */
    private Date expireDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_viainfo.data_from
     *
     * @mbg.generated
     */
    private Byte dataFrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_viainfo.success_flag
     *
     * @mbg.generated
     */
    private Byte successFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_viainfo.send_msg
     *
     * @mbg.generated
     */
    private String sendMsg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_viainfo.send_error
     *
     * @mbg.generated
     */
    private String sendError;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_viainfo.id
     *
     * @return the value of t_user_viainfo.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_viainfo.id
     *
     * @param id the value for t_user_viainfo.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_viainfo.user_id
     *
     * @return the value of t_user_viainfo.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_viainfo.user_id
     *
     * @param userId the value for t_user_viainfo.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_viainfo.receiver
     *
     * @return the value of t_user_viainfo.receiver
     *
     * @mbg.generated
     */
    public String getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_viainfo.receiver
     *
     * @param receiver the value for t_user_viainfo.receiver
     *
     * @mbg.generated
     */
    public void setReceiver(String receiver) {
        this.receiver = receiver == null ? null : receiver.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_viainfo.via_type
     *
     * @return the value of t_user_viainfo.via_type
     *
     * @mbg.generated
     */
    public Byte getViaType() {
        return viaType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_viainfo.via_type
     *
     * @param viaType the value for t_user_viainfo.via_type
     *
     * @mbg.generated
     */
    public void setViaType(Byte viaType) {
        this.viaType = viaType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_viainfo.via_text
     *
     * @return the value of t_user_viainfo.via_text
     *
     * @mbg.generated
     */
    public String getViaText() {
        return viaText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_viainfo.via_text
     *
     * @param viaText the value for t_user_viainfo.via_text
     *
     * @mbg.generated
     */
    public void setViaText(String viaText) {
        this.viaText = viaText == null ? null : viaText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_viainfo.create_date
     *
     * @return the value of t_user_viainfo.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_viainfo.create_date
     *
     * @param createDate the value for t_user_viainfo.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_viainfo.expire_date
     *
     * @return the value of t_user_viainfo.expire_date
     *
     * @mbg.generated
     */
    public Date getExpireDate() {
        return expireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_viainfo.expire_date
     *
     * @param expireDate the value for t_user_viainfo.expire_date
     *
     * @mbg.generated
     */
    public void setExpireDate(Date expireDate) {
        this.expireDate = expireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_viainfo.data_from
     *
     * @return the value of t_user_viainfo.data_from
     *
     * @mbg.generated
     */
    public Byte getDataFrom() {
        return dataFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_viainfo.data_from
     *
     * @param dataFrom the value for t_user_viainfo.data_from
     *
     * @mbg.generated
     */
    public void setDataFrom(Byte dataFrom) {
        this.dataFrom = dataFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_viainfo.success_flag
     *
     * @return the value of t_user_viainfo.success_flag
     *
     * @mbg.generated
     */
    public Byte getSuccessFlag() {
        return successFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_viainfo.success_flag
     *
     * @param successFlag the value for t_user_viainfo.success_flag
     *
     * @mbg.generated
     */
    public void setSuccessFlag(Byte successFlag) {
        this.successFlag = successFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_viainfo.send_msg
     *
     * @return the value of t_user_viainfo.send_msg
     *
     * @mbg.generated
     */
    public String getSendMsg() {
        return sendMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_viainfo.send_msg
     *
     * @param sendMsg the value for t_user_viainfo.send_msg
     *
     * @mbg.generated
     */
    public void setSendMsg(String sendMsg) {
        this.sendMsg = sendMsg == null ? null : sendMsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_viainfo.send_error
     *
     * @return the value of t_user_viainfo.send_error
     *
     * @mbg.generated
     */
    public String getSendError() {
        return sendError;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_viainfo.send_error
     *
     * @param sendError the value for t_user_viainfo.send_error
     *
     * @mbg.generated
     */
    public void setSendError(String sendError) {
        this.sendError = sendError == null ? null : sendError.trim();
    }
}