package com.fruit.app.service;

import com.fruit.app.model.TUserViainfo;
import com.fruit.app.model.TUserViainfoExample;

/**
 * 用户验证信息
 * Created by zoyation on 2017-09-04.
 */
public interface IUserViainfoService {
    /**
     * 发送验证信息
     * @param mobilePhone 手机号
     * @param viaInfo 验证信息
     * @return 是否成功
     */
    boolean sendMobileViaCode(String mobilePhone, String viaInfo);

    /**
     * 保存验证信息
     * @param userViainfo 验证信息
     * @return 影响数据行数
     */
    int saveViaInfo(TUserViainfo userViainfo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_viainfo
     *
     * @mbg.generated
     */
    long countByExample(TUserViainfoExample example);
}
