package com.fruit.app.dao;

import com.fruit.app.model.TGoodsWatch;
import com.fruit.app.model.TGoodsWatchExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TGoodsWatchMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_watch
     *
     * @mbg.generated
     */
    long countByExample(TGoodsWatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_watch
     *
     * @mbg.generated
     */
    int deleteByExample(TGoodsWatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_watch
     *
     * @mbg.generated
     */
    int insert(TGoodsWatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_watch
     *
     * @mbg.generated
     */
    int insertSelective(TGoodsWatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_watch
     *
     * @mbg.generated
     */
    List<TGoodsWatch> selectByExample(TGoodsWatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_watch
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TGoodsWatch record, @Param("example") TGoodsWatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_watch
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TGoodsWatch record, @Param("example") TGoodsWatchExample example);
}