package com.fruit.app.dao;

import com.fruit.app.model.TGoodsLocation;
import com.fruit.app.model.TGoodsLocationExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TGoodsLocationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_location
     *
     * @mbg.generated
     */
    long countByExample(TGoodsLocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_location
     *
     * @mbg.generated
     */
    int deleteByExample(TGoodsLocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_location
     *
     * @mbg.generated
     */
    int insert(TGoodsLocation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_location
     *
     * @mbg.generated
     */
    int insertSelective(TGoodsLocation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_location
     *
     * @mbg.generated
     */
    List<TGoodsLocation> selectByExampleWithBLOBs(TGoodsLocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_location
     *
     * @mbg.generated
     */
    List<TGoodsLocation> selectByExample(TGoodsLocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_location
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TGoodsLocation record, @Param("example") TGoodsLocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_location
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") TGoodsLocation record, @Param("example") TGoodsLocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_location
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TGoodsLocation record, @Param("example") TGoodsLocationExample example);
}