package com.fruit.app.dao;

import com.fruit.app.model.TGoodsPic;
import com.fruit.app.model.TGoodsPicExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TGoodsPicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_pic
     *
     * @mbg.generated
     */
    long countByExample(TGoodsPicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_pic
     *
     * @mbg.generated
     */
    int deleteByExample(TGoodsPicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_pic
     *
     * @mbg.generated
     */
    int insert(TGoodsPic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_pic
     *
     * @mbg.generated
     */
    int insertSelective(TGoodsPic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_pic
     *
     * @mbg.generated
     */
    List<TGoodsPic> selectByExample(TGoodsPicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_pic
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TGoodsPic record, @Param("example") TGoodsPicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_pic
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TGoodsPic record, @Param("example") TGoodsPicExample example);
}