package com.fruit.app.dao;

import com.fruit.app.model.TGoods;
import com.fruit.app.model.TGoodsExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods
     *
     * @mbg.generated
     */
    long countByExample(TGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods
     *
     * @mbg.generated
     */
    int deleteByExample(TGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods
     *
     * @mbg.generated
     */
    int insert(TGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods
     *
     * @mbg.generated
     */
    int insertSelective(TGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods
     *
     * @mbg.generated
     */
    List<TGoods> selectByExample(TGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TGoods record, @Param("example") TGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TGoods record, @Param("example") TGoodsExample example);
}