package com.fruit.app.dao;

import com.fruit.app.model.TGoodsScore;
import com.fruit.app.model.TGoodsScoreExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TGoodsScoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_score
     *
     * @mbg.generated
     */
    long countByExample(TGoodsScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_score
     *
     * @mbg.generated
     */
    int deleteByExample(TGoodsScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_score
     *
     * @mbg.generated
     */
    int insert(TGoodsScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_score
     *
     * @mbg.generated
     */
    int insertSelective(TGoodsScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_score
     *
     * @mbg.generated
     */
    List<TGoodsScore> selectByExampleWithBLOBs(TGoodsScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_score
     *
     * @mbg.generated
     */
    List<TGoodsScore> selectByExample(TGoodsScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_score
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TGoodsScore record, @Param("example") TGoodsScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_score
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") TGoodsScore record, @Param("example") TGoodsScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_score
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TGoodsScore record, @Param("example") TGoodsScoreExample example);
}