package com.fruit.app.dao;

import com.fruit.app.model.TSysLog;
import com.fruit.app.model.TSysLogExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TSysLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_log
     *
     * @mbg.generated
     */
    long countByExample(TSysLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_log
     *
     * @mbg.generated
     */
    int deleteByExample(TSysLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_log
     *
     * @mbg.generated
     */
    int insert(TSysLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_log
     *
     * @mbg.generated
     */
    int insertSelective(TSysLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_log
     *
     * @mbg.generated
     */
    List<TSysLog> selectByExampleWithBLOBs(TSysLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_log
     *
     * @mbg.generated
     */
    List<TSysLog> selectByExample(TSysLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TSysLog record, @Param("example") TSysLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_log
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") TSysLog record, @Param("example") TSysLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TSysLog record, @Param("example") TSysLogExample example);
}