package com.fruit.app.dao;

import com.fruit.app.model.TUserLocation;
import com.fruit.app.model.TUserLocationExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TUserLocationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_location
     *
     * @mbg.generated
     */
    long countByExample(TUserLocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_location
     *
     * @mbg.generated
     */
    int deleteByExample(TUserLocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_location
     *
     * @mbg.generated
     */
    int insert(TUserLocation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_location
     *
     * @mbg.generated
     */
    int insertSelective(TUserLocation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_location
     *
     * @mbg.generated
     */
    List<TUserLocation> selectByExampleWithBLOBs(TUserLocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_location
     *
     * @mbg.generated
     */
    List<TUserLocation> selectByExample(TUserLocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_location
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TUserLocation record, @Param("example") TUserLocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_location
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") TUserLocation record, @Param("example") TUserLocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_location
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TUserLocation record, @Param("example") TUserLocationExample example);
}