package com.fruit.app.dao;

import com.fruit.app.model.TUserOrder;
import com.fruit.app.model.TUserOrderExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TUserOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_order
     *
     * @mbg.generated
     */
    long countByExample(TUserOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_order
     *
     * @mbg.generated
     */
    int deleteByExample(TUserOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_order
     *
     * @mbg.generated
     */
    int insert(TUserOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_order
     *
     * @mbg.generated
     */
    int insertSelective(TUserOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_order
     *
     * @mbg.generated
     */
    List<TUserOrder> selectByExample(TUserOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_order
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TUserOrder record, @Param("example") TUserOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_order
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TUserOrder record, @Param("example") TUserOrderExample example);
}